//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDMUOJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContestRanking
    {
        public int id { get; set; }
        public int contestId { get; set; }
        public int rankingId { get; set; }
    
        public virtual Contest Contest { get; set; }
        public virtual Ranking Ranking { get; set; }
    }
}
