//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDMUOJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContestParticipant
    {
        public int id { get; set; }
        public int contestId { get; set; }
        public int memberId { get; set; }
        public Nullable<int> seed { get; set; }
        public Nullable<int> score { get; set; }
        public Nullable<int> penalty { get; set; }
        public Nullable<int> currentRating { get; set; }
        public Nullable<int> ratingChange { get; set; }
        public bool isVirtual { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Contest Contest { get; set; }
    }
}
