//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDMUOJ.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TDMUOJEntities : DbContext
    {
        public TDMUOJEntities()
            : base("name=TDMUOJEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Contest> Contests { get; set; }
        public virtual DbSet<ContestOrganizer> ContestOrganizers { get; set; }
        public virtual DbSet<ContestParticipant> ContestParticipants { get; set; }
        public virtual DbSet<ContestProblem> ContestProblems { get; set; }
        public virtual DbSet<ContestRanking> ContestRankings { get; set; }
        public virtual DbSet<Follower> Followers { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Problem> Problems { get; set; }
        public virtual DbSet<ProblemExample> ProblemExamples { get; set; }
        public virtual DbSet<ProblemSolved> ProblemSolveds { get; set; }
        public virtual DbSet<ProblemTestCase> ProblemTestCases { get; set; }
        public virtual DbSet<ResetPassword> ResetPasswords { get; set; }
        public virtual DbSet<Submission> Submissions { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<TagProblem> TagProblems { get; set; }
        public virtual DbSet<Ranking> Rankings { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
    }
}
