//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDMUOJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTPVerification
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string OTPCode { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public Nullable<bool> IsUsed { get; set; }
    }
}
