//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDMUOJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submission
    {
        public int id { get; set; }
        public int problemId { get; set; }
        public int userId { get; set; }
        public string code { get; set; }
        public string language { get; set; }
        public Nullable<double> maxTime { get; set; }
        public Nullable<double> maxMemory { get; set; }
        public string result { get; set; }
        public Nullable<System.DateTime> submittedAt { get; set; }
        public Nullable<int> testCaseTotal { get; set; }
        public Nullable<int> testCaseAchieved { get; set; }
        public Nullable<int> contestId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Problem Problem { get; set; }
    }
}
