//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDMUOJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagProblem
    {
        public int id { get; set; }
        public int tagId { get; set; }
        public int problemId { get; set; }
    
        public virtual Problem Problem { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
